DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),

]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('Заголовок', max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'Посты'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    pass

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .models import Post


def post_list(request):
    posts = Post.objects.filter(publish_date__lte=timezone.now()).order_by(
        'publish_date'
    )
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

users/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Django blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  </head>
  <body>
    <header class="page-header">
      <div class="container">
        <h1><a href="/">Django Blog</a></h1>
      </div>
    </header>
    <main class="container">
      <div class="row">
        <div class="col">
        {% block content %}
        {% endblock %}
        </div>
      </div>
    </main>
  </body>
</html>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        {% if post.publish_date %}
            <time class="date">
                {{ post.publish_date }}
            </time>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </article>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
  {% for post in posts %}
    <article class="post">
      <time class="date">
        {{ post.publish_date }}
      </time>
      <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
      </h2>
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
  {% endfor %}
{% endblock %}